# Simple Theme Configuration
menu:
  首页: /
  归档: /archives
  关于: /about

# Sidebar
sidebar: right

# Social Links
social:
  GitHub: https://github.com/
  Twitter: https://twitter.com/

# Footer
footer:
  copyright: © 2025 创业思考博客